SELECT 'Create user "maupdater" ';

CREATE ROLE maupdater WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;
  
SELECT 'Create user "navtech" '; 

CREATE ROLE navtech WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION;
  
SELECT 'Create user "web_api" '; 

CREATE ROLE web_api WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;
  
SELECT 'Create user "windows_service" '; 

CREATE ROLE windows_service WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;
  
SELECT 'Create user "repuser" '; 

CREATE ROLE repuser WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION;  