SELECT 'Create user "db_designer" '; 

CREATE ROLE db_designer WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION;
  
SELECT 'Create user "web_api" '; 

CREATE ROLE web_api WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;
  
SELECT 'Create user "windows_service" '; 

CREATE ROLE windows_service WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;
