
version: '3.8'

services:
  pg-master:
    container_name: pg-docker
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'on-failure'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'docker'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - type: bind
        source: '../../../volumes/pg-docker'
        target: '/var/lib/postgresql/data'
    ports:
      - target: 5432
        published: 9876
        mode: host